print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/s651188/Documents/GitHub/Lab1/Assets/SuperDuperSecretAnimation (1).mb"`)
{		
	file -o "/Users/s651188/Documents/GitHub/Lab1/Assets/SuperDuperSecretAnimation (1).mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/s651188/Documents/GitHub/Lab1/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "/Users/s651188/Documents/GitHub/Lab1/Temp/CommandPipe";

$donepipeKill = `fopen "/Users/s651188/Documents/GitHub/Lab1/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
